version: "3"
services:
  app-auth-server:
    build:
      context: .
      dockerfile: dockerfile.prod
    working_dir: /app
    command: poetry run gunicorn --bind 0.0.0.0:8000 DjangoAuth.wsgi
    ports:
      - "8000:8000"
    networks:
      - auth-network
    depends_on:
      db:
        condition: service_started
  db:
    container_name: db
    image: mysql:8

    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_TCP_PORT=${DATABASE_PORT}
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    networks:
      - auth-network
    ports:
      - "3308:3308"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Nginx:/etc/nginx/conf.d
    depends_on:
      - app-auth-server
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
