# Generated by Django 4.2.5 on 2023-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='service',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
