# Generated by Django 4.2.5 on 2023-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
