# Generated by Django 4.2.5 on 2023-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_userprofiles_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
