# Generated by Django 4.2.5 on 2023-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_userprofiles_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
