# Generated by Django 4.2.5 on 2023-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userprofiles_is_active_userprofiles_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
