# Generated by Django 4.2.5 on 2023-09-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_useraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='Address',
        ),
    ]
