# Generated by Django 4.2.5 on 2023-11-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_user_id_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='customer_omise_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
